// Analyst V2.6 semantic layer — evidence, confidence & deterministic completeness.
const upstreamFetch=global.fetch;
const ANTHROPIC_URL='https://api.anthropic.com/v1/messages';
const PRESENTATION_SYSTEM='You output only the JSON object described in the instructions below — no other text.';
const ANALYST_SYSTEM_MARKER='You are the quantitative analyst for Qimam AI Sales';
function parseLoose(text){return JSON.parse(String(text||'').replace(/^```json\s*/i,'').replace(/^```\s*/,'').replace(/```\s*$/,'').trim())}
function parseJsonPrefix(text){const s=String(text||'').trimStart(),start=s.search(/[\[{]/);if(start<0)throw new Error('No JSON prefix found');const open=s[start],close=open==='{'?'}':']';let depth=0,inString=false,escaped=false;for(let i=start;i<s.length;i++){const ch=s[i];if(inString){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch==='"')inString=false;continue}if(ch==='"'){inString=true;continue}if(ch===open)depth++;else if(ch===close){depth--;if(depth===0)return JSON.parse(s.slice(start,i+1))}}throw new Error('Unterminated JSON prefix')}
function extractPresentationEnvelope(body){if(!body||body.system!==PRESENTATION_SYSTEM||!Array.isArray(body.messages))return null;const msg=body.messages[body.messages.length-1];if(!msg||typeof msg.content!=='string')return null;const text=msg.content,q='Original question:\n',p='\n\nExecuted Odoo MCP plan:\n',r='\n\nLIVE factual Odoo results:\n',qi=text.indexOf(q),pi=text.indexOf(p),ri=text.indexOf(r);if(qi<0||pi<0||ri<0||!(qi<pi&&pi<ri))return null;try{return{question:text.slice(qi+q.length,pi).trim(),plan:JSON.parse(text.slice(pi+p.length,ri).trim()),results:parseJsonPrefix(text.slice(ri+r.length))}}catch(e){console.error('analyst-preload envelope parse error:',e.message);return null}}
function normalizeEvidence(x){if(!Array.isArray(x))return[];return x.slice(0,12).map(v=>typeof v==='string'?v:(v&&typeof v==='object'?v:null)).filter(Boolean)}
function normalizeStatement(v,defaultType='derived'){if(typeof v==='string')return{text:v,type:defaultType,confidence:defaultType==='hypothesis'?'low':'high',evidence:[]};if(!v||typeof v!=='object')return null;const type=['fact','derived','hypothesis'].includes(v.type)?v.type:defaultType;let confidence=['high','medium','low'].includes(v.confidence)?v.confidence:(type==='hypothesis'?'low':'high');if(type==='hypothesis'&&confidence==='high')confidence='medium';return{...v,type,confidence,evidence:normalizeEvidence(v.evidence)}}
function normalizeStatements(arr,defaultType){return Array.isArray(arr)?arr.slice(0,20).map(x=>normalizeStatement(x,defaultType)).filter(Boolean):[]}
function resultEntries(results){if(Array.isArray(results))return results.map((v,i)=>[String(v?.name||v?.operation||v?.id||`operation_${i+1}`),v]);if(results&&typeof results==='object')return Object.entries(results);return[]}
function hasError(v){if(!v||typeof v!=='object')return false;if(v.error||v.errors||v.ok===false||v.success===false)return true;const s=String(v.status||'').toLowerCase();return ['error','failed','failure'].includes(s)}
function assessCompleteness(envelope){const planned=Array.isArray(envelope?.plan?.operations)?envelope.plan.operations.length:0,entries=resultEntries(envelope?.results),failed=entries.filter(([,v])=>hasError(v)).map(([k,v])=>({operation:k,error:String(v?.error||v?.message||v?.status||'operation failed').slice(0,240)}));let status='complete';if(!entries.length)status='insufficient';else if(failed.length)status=failed.length>=entries.length?'insufficient':'partial';else if(planned&&entries.length<planned)status='partial';return{version:'1.0',status,plannedOperations:planned,returnedOperations:entries.length,failedOperations:failed,reason:status==='complete'?'All returned MCP operations completed without an explicit error.':status==='partial'?'Some planned or returned MCP evidence is missing or failed.':'No usable complete MCP evidence was returned.'}}
function safeAnalysis(a,completeness){if(!a||typeof a!=='object')return null;let answer=['complete','partial','insufficient'].includes(a.answerability)?a.answerability:'partial';if(completeness.status==='insufficient')answer='insufficient';else if(completeness.status==='partial'&&answer==='complete')answer='partial';return{version:'2.6',answerability:answer,completeness,scope:a.scope&&typeof a.scope==='object'?a.scope:{},facts:normalizeStatements(a.facts,'fact').slice(0,40),derivedMetrics:Array.isArray(a.derivedMetrics)?a.derivedMetrics.slice(0,30).map(x=>x&&typeof x==='object'?{...x,type:'derived',confidence:['high','medium','low'].includes(x.confidence)?x.confidence:'high',evidence:normalizeEvidence(x.evidence)}:x):[],rankings:Array.isArray(a.rankings)?a.rankings.slice(0,12):[],comparisons:Array.isArray(a.comparisons)?a.comparisons.slice(0,12):[],trends:normalizeStatements(a.trends,'derived').slice(0,12),anomalies:normalizeStatements(a.anomalies,'derived').slice(0,12),insights:normalizeStatements(a.insights,'derived').slice(0,12),caveats:normalizeStatements(a.caveats,'fact').slice(0,12)}}
async function runAnalyst(envelope,originalBody){const apiKey=process.env.ANTHROPIC_API_KEY||'';if(!apiKey)return null;const completeness=assessCompleteness(envelope),model=process.env.ANTHROPIC_MODEL||originalBody.model||'claude-sonnet-4-6';const system=`${ANALYST_SYSTEM_MARKER}. Analysis only. Return ONLY JSON with keys: answerability, scope, facts, derivedMetrics, rankings, comparisons, trends, anomalies, insights, caveats.\n\nDATA COMPLETENESS V2.6:\n- A deterministic pre-check is supplied as MCP_COMPLETENESS. Respect it as a hard floor: if partial, answerability cannot be complete; if insufficient, answerability must be insufficient.\n- Never fill missing/failed operation evidence by inference. Clearly caveat which requested analysis cannot be supported.\n- Empty legitimate business results are not automatically errors; explicit tool errors/missing planned operation results are completeness problems.\n\nEVIDENCE & CONFIDENCE:\n- Statements in facts,trends,anomalies,insights,caveats are {text,type,confidence,evidence}; type fact|derived|hypothesis; confidence high|medium|low. Hypotheses never high and never worded as facts.\n- Use only supplied MCP evidence and deterministic arithmetic. Preserve exact scope.\n- derivedMetrics: {name,value,unit,formula,inputs,status,type,confidence,evidence}; status valid|not_applicable|insufficient.\n- Percentage change=(current-base)/base*100 only if base!=0; base=0 => not_applicable,value=null. Keep absolute difference separate. Shares/averages require compatible denominators.\n- contribution_to_change=current_entity-previous_entity. Rankings state metric,direction,scope and sorted items {rank,label,value,secondaryValue}.\n- Missing evidence, zero-base ratios, incompatible scopes and ambiguity belong in caveats. No markdown/UI/chart instructions.`;const user=`Question:\n${envelope.question}\n\nMCP_COMPLETENESS:\n${JSON.stringify(completeness)}\n\nExecuted plan:\n${JSON.stringify(envelope.plan)}\n\nLIVE MCP evidence:\n${JSON.stringify(envelope.results)}`;const resp=await upstreamFetch(ANTHROPIC_URL,{method:'POST',headers:{'content-type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:4000,system,messages:[{role:'user',content:user}]})});if(!resp.ok)return null;try{const payload=await resp.json(),text=(payload.content||[]).map(x=>x.text||'').join('').trim();return safeAnalysis(parseLoose(text),completeness)}catch(e){console.error('analyst-preload analysis parse error:',e.message);return null}}
global.fetch=async function analystFetch(url,options={}){let body=null,envelope=null;try{if(String(url).includes('api.anthropic.com/v1/messages')&&options.body){body=JSON.parse(options.body);if(!String(body.system||'').includes(ANALYST_SYSTEM_MARKER))envelope=extractPresentationEnvelope(body)}}catch{}if(envelope&&body){try{const analysis=await runAnalyst(envelope,body);if(analysis){const msg=body.messages[body.messages.length-1];msg.content+=`\n\nANALYST V2.6 — AUTHORITATIVE SEMANTIC ANALYSIS:\n${JSON.stringify(analysis)}\n\nANSWERABILITY & COMPLETENESS — HARD REQUIREMENT:\n- Preserve analyst.answerability exactly. Never present a partial/insufficient result as complete.\n- If partial, state briefly that the analysis is partial and avoid unsupported conclusions. If insufficient, clearly say available evidence is insufficient and do not fabricate KPIs/charts for missing facts.\n- MCP raw facts remain authoritative. Analyst derived metrics/comparisons/rankings are authoritative. Preserve not_applicable/insufficient and evidence confidence. Hypotheses remain possibilities only.\n\nRANKING CONSISTENCY:\nFor the same metric/scope use analyst ranking item order consistently across charts/tables/narrative; never sort labels separately from values.`;options={...options,body:JSON.stringify(body)}}}catch(e){console.error('analyst-preload non-fatal error:',e.message)}}return upstreamFetch(url,options)};
require('./presentation-validator-preload.js');
