'use strict';
const assert=require('assert');
const {buildDatasetCatalog,compactCatalog}=require('../presentation-v4-catalog');
const plan={operations:[{name:'monthly_sales',arguments:{model:'sale.order',groupby:['date_order:month']}},{name:'top_customers',arguments:{model:'sale.order',groupby:['partner_id']}}]};
const results={monthly_sales:{rows:[{'date_order:month':'2025-06-01 00:00:00','amount_total:sum':100},{'date_order:month':'2025-07-01 00:00:00','amount_total:sum':200}]},top_customers:{rows:[{partner_id:[1,'A'],'amount_total:sum':250,'__count':2}]}};
const {datasets,catalog}=buildDatasetCatalog(plan,results,{sampleRows:1});
assert.strictEqual(datasets.monthly_sales.rows.length,2);
assert.strictEqual(catalog.length,2);
assert.strictEqual(catalog[0].rowCount,2);
assert.strictEqual(catalog[0].groupby[0],'date_order:month');
const amount=catalog[0].fields.find(f=>f.name==='amount_total:sum');
assert.strictEqual(amount.type,'number');
assert.strictEqual(amount.numeric.sum,300);
const partner=catalog[1].fields.find(f=>f.name==='partner_id');
assert.strictEqual(partner.type,'many2one');
assert.deepStrictEqual(partner.distinctSample,['A']);
const compact=compactCatalog(catalog);
assert.strictEqual(Object.prototype.hasOwnProperty.call(compact[0],'sample'),false);
console.log('presentation-v4-catalog tests: OK');
